name: sample

on:
  push:
    branches:
      - master

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v3.0.0
      - name: Install plugin
        run: pip install pytest-github-actions-annotate-failures
      - name: Test with pytest
        run: |
          pytest --alluredir=allure-results --browser chrome_headless


      - name: Run Code
        run: python Slearnings/ExpediaAgain.py
